{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Perception at step 1 is [dirty,A]\n",
      "None\n",
      "------- Action taken  at step 1 is [clean]\n",
      "Perception at step 2 is [clean,A]\n",
      "None\n",
      "------- Action taken  at step 2 is [right]\n",
      "Perception at step 3 is [dirty,B]\n",
      "None\n",
      "------- Action taken  at step 3 is [clean]\n",
      "Perception at step 4 is [clean,B]\n",
      "None\n",
      "------- Action taken  at step 4 is [left]\n",
      "Perception at step 5 is [clean,B]\n",
      "None\n",
      "------- Action taken  at step 5 is [left]\n",
      "Perception at step 6 is [clean,B]\n",
      "None\n",
      "------- Action taken  at step 6 is [left]\n",
      "Perception at step 7 is [clean,B]\n",
      "None\n",
      "------- Action taken  at step 7 is [left]\n",
      "Perception at step 8 is [clean,B]\n",
      "None\n",
      "------- Action taken  at step 8 is [left]\n",
      "Perception at step 9 is [clean,B]\n",
      "None\n",
      "------- Action taken  at step 9 is [left]\n",
      "Perception at step 10 is [clean,B]\n",
      "None\n",
      "------- Action taken  at step 10 is [left]\n",
      "Perception at step 11 is [clean,B]\n",
      "None\n",
      "------- Action taken  at step 11 is [left]\n",
      "Perception at step 12 is [clean,B]\n",
      "None\n",
      "------- Action taken  at step 12 is [left]\n",
      "Perception at step 13 is [clean,B]\n",
      "None\n",
      "------- Action taken  at step 13 is [left]\n",
      "Perception at step 14 is [clean,B]\n",
      "None\n",
      "------- Action taken  at step 14 is [left]\n",
      "Perception at step 15 is [clean,B]\n",
      "None\n",
      "------- Action taken  at step 15 is [left]\n",
      "Perception at step 16 is [clean,B]\n",
      "None\n",
      "------- Action taken  at step 16 is [left]\n",
      "Perception at step 17 is [clean,B]\n",
      "None\n",
      "------- Action taken  at step 17 is [left]\n",
      "Perception at step 18 is [clean,B]\n",
      "None\n",
      "------- Action taken  at step 18 is [left]\n",
      "Perception at step 19 is [clean,B]\n",
      "None\n",
      "------- Action taken  at step 19 is [left]\n",
      "Perception at step 20 is [clean,B]\n",
      "None\n",
      "------- Action taken  at step 20 is [left]\n",
      "Perception at step 21 is [clean,B]\n",
      "None\n",
      "------- Action taken  at step 21 is [left]\n",
      "Perception at step 22 is [clean,B]\n",
      "None\n",
      "------- Action taken  at step 22 is [left]\n",
      "Perception at step 23 is [clean,B]\n",
      "None\n",
      "------- Action taken  at step 23 is [left]\n",
      "Perception at step 24 is [clean,B]\n",
      "None\n",
      "------- Action taken  at step 24 is [left]\n",
      "Perception at step 25 is [clean,B]\n",
      "None\n",
      "------- Action taken  at step 25 is [left]\n",
      "Perception at step 26 is [clean,B]\n",
      "None\n",
      "------- Action taken  at step 26 is [left]\n",
      "Perception at step 27 is [clean,B]\n",
      "None\n",
      "------- Action taken  at step 27 is [left]\n",
      "Perception at step 28 is [clean,B]\n",
      "None\n",
      "------- Action taken  at step 28 is [left]\n",
      "Perception at step 29 is [clean,B]\n",
      "None\n",
      "------- Action taken  at step 29 is [left]\n",
      "Perception at step 30 is [clean,B]\n",
      "None\n",
      "------- Action taken  at step 30 is [left]\n",
      "Perception at step 31 is [clean,B]\n",
      "None\n",
      "------- Action taken  at step 31 is [left]\n",
      "Perception at step 32 is [clean,B]\n",
      "None\n",
      "------- Action taken  at step 32 is [left]\n",
      "Perception at step 33 is [clean,B]\n",
      "None\n",
      "------- Action taken  at step 33 is [left]\n",
      "Perception at step 34 is [clean,B]\n",
      "None\n",
      "------- Action taken  at step 34 is [left]\n",
      "Perception at step 35 is [clean,B]\n",
      "None\n",
      "------- Action taken  at step 35 is [left]\n",
      "Perception at step 36 is [clean,B]\n",
      "None\n",
      "------- Action taken  at step 36 is [left]\n",
      "Perception at step 37 is [clean,B]\n",
      "None\n",
      "------- Action taken  at step 37 is [left]\n",
      "Perception at step 38 is [clean,B]\n",
      "None\n",
      "------- Action taken  at step 38 is [left]\n",
      "Perception at step 39 is [clean,B]\n",
      "None\n",
      "------- Action taken  at step 39 is [left]\n",
      "Perception at step 40 is [clean,B]\n",
      "None\n",
      "------- Action taken  at step 40 is [left]\n",
      "Perception at step 41 is [clean,B]\n",
      "None\n",
      "------- Action taken  at step 41 is [left]\n",
      "Perception at step 42 is [clean,B]\n",
      "None\n",
      "------- Action taken  at step 42 is [left]\n",
      "Perception at step 43 is [clean,B]\n",
      "None\n",
      "------- Action taken  at step 43 is [left]\n",
      "Perception at step 44 is [clean,B]\n",
      "None\n",
      "------- Action taken  at step 44 is [left]\n",
      "Perception at step 45 is [clean,B]\n",
      "None\n",
      "------- Action taken  at step 45 is [left]\n",
      "Perception at step 46 is [clean,B]\n",
      "None\n",
      "------- Action taken  at step 46 is [left]\n",
      "Perception at step 47 is [clean,B]\n",
      "None\n",
      "------- Action taken  at step 47 is [left]\n",
      "Perception at step 48 is [clean,B]\n",
      "None\n",
      "------- Action taken  at step 48 is [left]\n",
      "Perception at step 49 is [clean,B]\n",
      "None\n",
      "------- Action taken  at step 49 is [left]\n",
      "Perception at step 50 is [clean,B]\n",
      "None\n",
      "------- Action taken  at step 50 is [left]\n"
     ]
    }
   ],
   "source": [
    "'''\n",
    "Created on Feb 11, 2019\n",
    "\n",
    "@author: dr.aarij\n",
    "'''\n",
    "\n",
    "import os\n",
    "os.chdir('C:/Users/umer.chawla/Desktop/Lab3')\n",
    "\n",
    "#print(os.getcwd())\n",
    "\n",
    "import VaccumAgent\n",
    "import Environment \n",
    "import Agent \n",
    "import Room\n",
    "\n",
    "\n",
    "class TwoRoomVaccumCleanerEnvironment():\n",
    "    '''\n",
    "    classdocs\n",
    "    '''\n",
    "    def __init__(self, agent):\n",
    "        '''\n",
    "        Constructor\n",
    "        '''\n",
    "        self.r1 = Room.Room('A','dirty')\n",
    "        self.r2 = Room.Room('B','dirty')\n",
    "        self.r3 = Room.Room('C','dirty')\n",
    "        self.agent = agent\n",
    "        self.currentRoom = self.r1\n",
    "        #self.delay = 1000\n",
    "        self.step = 1\n",
    "        self.action = \"\"\n",
    "    \n",
    "    def executeStep(self,n=1):\n",
    "        for _ in range(0,n):\n",
    "            self.displayPerception()\n",
    "            self.agent.sense(self)\n",
    "            res = self.agent.act()\n",
    "            self.action = res\n",
    "            if res == 'clean':\n",
    "                self.currentRoom.status = 'clean'\n",
    "            elif res == 'move to B':\n",
    "                self.currentRoom = self.r3\n",
    "            elif res == 'move to C':\n",
    "                self.currentRoom = self.r3\n",
    "            else:\n",
    "                self.currentRoom = self.r2\n",
    "            self.displayAction()\n",
    "            self.step += 1\n",
    "        \n",
    "    \n",
    "    def executeAll(self):\n",
    "        raise NotImplementedError('action must be defined!')\n",
    "    \n",
    "    def displayPerception(self):\n",
    "        print(\"Perception at step %d is [%s,%s]\" %(self.step,self.currentRoom.status,self.currentRoom.location))\n",
    "        \n",
    "    def displayAction(self):\n",
    "        print(\"------- Action taken  at step %d is [%s]\" %(self.step,self.action))\n",
    "    \n",
    "   # def delay(self, n=100):\n",
    "      #  self.delay = n\n",
    "        \n",
    "if __name__ == '__main__':\n",
    "    vcagent = VaccumAgent.VaccumAgent() \n",
    "    env = TwoRoomVaccumCleanerEnvironment(vcagent)\n",
    "    env.executeStep(50) \n",
    "    \n",
    "    \n",
    "    \n",
    "    \n",
    "    \n",
    "    "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
